version: '3.8'

services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./public:/var/www/html
    depends_on:
      - workspace

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: homestead
      MYSQL_USER: homestead
      MYSQL_PASSWORD: secret
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_USER: homestead
      PMA_PASSWORD: secret
    ports:
      - "8080:80"
    depends_on:
      - mysql

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  workspace:
    image: php:7.4-fpm
    volumes:
      - ./public:/var/www/html
    depends_on:
      - mysql
      - redis

volumes:
  mysql-data:
